# Generated by Django 5.2 on 2025-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_year',
            field=models.CharField(choices=[('S1', 'Senior 1'), ('S2', 'Senior 2'), ('S3', 'Senior 3'), ('S4', 'Senior 4'), ('S5', 'Senior 5'), ('S6', 'Senior 6')], default=2025, max_length=2),
            preserve_default=False,
        ),
    ]
