# Generated by Django 5.2 on 2025-09-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_class_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stream',
            new_name='combination',
        ),
    ]
