# Generated by Django 5.2 on 2025-09-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_stream_student_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_subsidiary',
            field=models.BooleanField(default=False),
        ),
    ]
